import sqlmodel

"""add_send_summary_to_self_to_group

Revision ID: b6ebf48dea6a
Revises: c7c2ed909f51
Create Date: 2025-11-01 19:37:25.378373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ebf48dea6a'
down_revision: Union[str, None] = 'c7c2ed909f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with default value False (groups don't receive their own summaries by default)
    op.add_column('group', sa.Column('send_summary_to_self', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Drop the forward_to_chat_jid column if it exists
    try:
        op.drop_column('group', 'forward_to_chat_jid')
    except Exception:
        pass  # Column might not exist if previous migration wasn't applied
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('forward_to_chat_jid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('group', 'send_summary_to_self')
    # ### end Alembic commands ###
